#!/bin/sh
JAVA=$(which java)
if [ ! -x "${JAVA}" ]; then
  echo "ERROR: java not found in PATH."
  exit 1
fi
VERSION=$(java -version 2>&1 | sed 's/.*version "\(.*\)\.\(.*\)\..*"/\1\2/; 1q')
if [ ! "$VERSION" -ge 18 ]; then
  echo "ERROR: Running fzn-oscar-cbls requires java version 1.8."
  exit 1
fi

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
exec java -Xmx2048M -cp "${SCRIPTPATH}/lib/*" oscar.flatzinc.cbls.FznOscarCbls "$@"
